trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
steps:
  # Sample command to test echo
  - script: echo This is a build pipeline using Azure-pipelines
  # This is a sample command to test mkdir
  - script: mkdir sampledir

  # Actual script needed for you.
  - script: |
        ls -ltr 
        az login --service-principal --username "75035e0c-4f46-4378-bf42-83e5b2326df9"  --password "115826a5-46ff-4a28-9e0c-cdbd601ddc5b" --tenant "20f3b949-2903-4d24-9d01-ad8df676e397"
        # Update for your admin password
        AdminPassword=Nareshbitla_1205
        rgName=myResourceGroup7
        locName=westeurope
        vnetName=myVnet7
        subnetName=mySubnet7
        publicIP=myPublicIP7
        nsgName=myNetworkSecurityGroup7
        nicName=myNic7
        vmName=myVM7
        userName=azureuser
        az group create --name $rgName --location $locName
        az network vnet create --resource-group $rgName --name $vnetName --subnet-name $subnetName
        az network public-ip create --resource-group $rgName --name $publicIP
        az network nsg create --resource-group $rgName --name $nsgName
        az network nic create \
           --resource-group $rgName \
           --name $nicName \
           --vnet-name $vnetName \
           --subnet $subnetName \
           --network-security-group $nsgName \
           --public-ip-address $publicIP
        az vm create \
           --resource-group $rgName \
           --name $vmName \
           --location $locName \
           --image OpenLogic:CentOS-CI:7-CI:latest \
           --admin-username $userName \
           --admin-password $AdminPassword \
           --generate-ssh-keys
           
        az vm run-command invoke -g $rgName -n $vmName --command-id RunShellScript --scripts "sudo touch /tmp/file1.txt && sudo curl -fsSL https://get.docker.com/ | sh"
        # az vm open-port --port 3389 --resource-group myResourceGroup --name myVM
